import type { Metadata } from "next";
import { Button, Calendar, Hero, InfoGrid, Section, Shell } from "../../_components/IconicPage";

export const metadata: Metadata = { title: "GROWN-ISH — ICONIC | Southlake Arena", description: "GROWN-ISH is ICONIC's recurring 21+ concert series at Southlake Arena." };

const southlake=[
{month:"JAN",date:"JAN 16",anchor:"MLK WEEKEND · SOUTHLAKE ARENA"},{month:"FEB",date:"FEB 27",anchor:"POST-SUPER BOWL / ALL-STAR · SOUTHLAKE ARENA"},{month:"MAR",date:"MAR 13",anchor:"SPRING KICKOFF · SOUTHLAKE ARENA"},{month:"APR",date:"APR 03",anchor:"SPRING · SOUTHLAKE ARENA"},{month:"MAY",date:"MAY 29",anchor:"MEMORIAL DAY WEEKEND · SOUTHLAKE ARENA"},{month:"JUN",date:"JUN 05",anchor:"EARLY SUMMER · SOUTHLAKE ARENA"},{month:"JUL",date:"JUL 10",anchor:"SUMMER · SOUTHLAKE ARENA"},{month:"AUG",date:"AUG 07",anchor:"LATE SUMMER · SOUTHLAKE ARENA"},{month:"SEP",date:"SEP 04",anchor:"LABOR DAY WEEKEND · SOUTHLAKE ARENA"},{month:"OCT",date:"OCT 02",anchor:"HBCU / HOMECOMING · SOUTHLAKE ARENA"},{month:"NOV",date:"NOV 12",anchor:"FALL · SOUTHLAKE ARENA"},{month:"DEC",date:"DEC 10",anchor:"HOLIDAY CONCERT · SOUTHLAKE ARENA"}];

export default function Page(){return <Shell><Hero eyebrow="ICONIC · SOUTHLAKE ARENA · 21+ SERIES" title="GROWN-ISH." sub="ICONIC's culture-forward 21+ concert series now has a defined home at Southlake Arena. Contemporary hip-hop, R&B, crossover talent, premium hospitality and a recurring arena experience built to become a habit."><Button href="#calendar">2027 Calendar</Button><Button href="/southlake-arena" ghost>Southlake Hub</Button></Hero><Section eyebrow="The Property" title="A recurring 21+ arena night, not a one-off concert."><InfoGrid items={[{label:"Audience",value:"21+",body:"Young adult concert and nightlife audience."},{label:"Home Venue",value:"Southlake Arena",body:"The permanent home base for the core series."},{label:"Sound",value:"Hip-Hop + R&B",body:"Contemporary headliners, crossover acts, DJs and rising talent."},{label:"Cadence",value:"12 Shows",body:"A full 2027 Southlake calendar, with national expansion handled separately."}]}/></Section><Section eyebrow="2027 · Southlake Arena" title="Twelve nights. One home venue." dark><div id="calendar" style={{maxWidth:980}}><Calendar rows={southlake} status="GROWN-ISH · SOUTHLAKE ARENA · 2027"/></div></Section><Section eyebrow="National Growth" title="Southlake is the flagship. ICONIC expands by market."><InfoGrid items={[{label:"Las Vegas",value:"4 Events",body:"Four ICONIC dates planned for the Las Vegas market."},{label:"Washington DC",value:"4 Events",body:"Four ICONIC dates planned for the DC market."},{label:"Tampa",value:"4 Events",body:"Four ICONIC dates planned for the Tampa market."},{label:"Rule",value:"Brand Stays Distinct",body:"GROWN-ISH keeps its own audience, creative identity and funnel under the ICONIC platform."}]}/></Section></Shell>}
