import type { Metadata } from "next";
import { Button, Calendar, Hero, InfoGrid, Section, Shell } from "../../_components/IconicPage";

export const metadata: Metadata = { title: "GROWN-ISH — ICONIC Atlanta", description: "GROWN-ISH is ICONIC's recurring 21+ Atlanta concert series." };

const atlanta=[
{month:"JAN",date:"JAN 16",anchor:"MLK WEEKEND"},{month:"FEB",date:"FEB 27",anchor:"POST-SUPER BOWL / ALL-STAR"},{month:"MAR",date:"MAR 13",anchor:"SPRING KICKOFF"},{month:"APR",date:"APR 03",anchor:"SPRING"},{month:"MAY",date:"MAY 29",anchor:"MEMORIAL DAY WEEKEND"},{month:"JUN",date:"JUN 05",anchor:"EARLY SUMMER"},{month:"JUL",date:"JUL 10",anchor:"SUMMER"},{month:"AUG",date:"AUG 07",anchor:"LATE SUMMER"},{month:"SEP",date:"SEP 04",anchor:"LABOR DAY WEEKEND"},{month:"OCT",date:"OCT 02",anchor:"HBCU / HOMECOMING"},{month:"NOV",date:"NOV 12",anchor:"FALL"},{month:"DEC",date:"DEC 10",anchor:"HOLIDAY CONCERT"}];

export default function Page(){return <Shell><Hero eyebrow="ICONIC ATLANTA · 21+ SERIES" title="GROWN-ISH." sub="Atlanta's culture-forward 21+ concert series. Contemporary hip-hop, R&B, crossover talent and a room built for the city after dark."><Button href="#calendar">2027 Calendar</Button><Button href="mailto:info@thekollectivehospitality.com?subject=GROWN-ISH%20Talent%20or%20Partnership" ghost>Talent / Partners</Button></Hero><Section eyebrow="The Property" title="Not just a concert. Atlanta's recurring night out."><InfoGrid items={[{label:"Audience",value:"21+",body:"Young adult nightlife and concert audience."},{label:"Market",value:"Atlanta",body:"A dedicated Atlanta property under ICONIC."},{label:"Sound",value:"Hip-Hop + R&B",body:"Contemporary headliners, crossover acts, DJs and rising talent."},{label:"Cadence",value:"12 Shows",body:"A full 2027 monthly calendar."}]}/></Section><Section eyebrow="2027" title="Twelve nights. One property." dark><div id="calendar" style={{maxWidth:920}}><Calendar rows={atlanta} status="GROWN-ISH · ATLANTA 2027"/></div></Section><Section eyebrow="Experience" title="Built for energy, discovery and repeat attendance."><InfoGrid items={[{label:"Headline",value:"Main Draw",body:"Every date has a clear artist or package driving ticket demand."},{label:"Support",value:"Culture Layer",body:"Local and emerging talent keeps every edition connected to Atlanta."},{label:"Nightlife",value:"After Dark",body:"DJ programming, premium tables and social energy extend the show beyond the set."},{label:"Retention",value:"Come Back",body:"Every buyer enters the next-date presale funnel."}]}/></Section></Shell>}
