import Link from 'next/link';
import type { ReactNode } from 'react';
import { ICONIC_LOGO } from '../_components/IconicPage';
import AccessForm from '../access/AccessForm';
import { getMerchCatalog, formatPrice } from '../tampa/nightmare-on-channelside/merch/catalog';
import { ART, WORLDS, COLLECTIONS, COLLECTION_ART, MERCH_ROOT } from './assets';
import MotionCanvas from './MotionCanvas';
import s from './cinematic.module.css';

const NAV = [['Events','/events'],['Experiences','/experiences'],['Music','/music'],['Creators','/creators'],['Merch','/merch'],['Partners','/partners']] as const;
export function CinematicShell({children, active = ''}:{children:ReactNode; active?:string}) {
  return <div className={s.site} data-design-version="2.0.0">
    <a className={s.skip} href="#iconic-content">Skip to content</a>
    <header className={s.header} data-testid="site-header">
      <Link href="/" className={s.logo} aria-label="ICONIC home"><img src={ICONIC_LOGO} alt="ICONIC" width={200} height={60}/></Link>
      <nav className={s.nav} aria-label="Main navigation">{NAV.map(([label,href])=><Link key={href} href={href} aria-current={active===href?'page':undefined}>{label}</Link>)}</nav>
      <div className={s.headerActions}><Link className={s.access} href="/access?intent=presale">Get access <span aria-hidden="true">↗</span></Link>
      <details className={s.mobileMenu}><summary aria-label="Open navigation">Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobile navigation">{NAV.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}<Link href="/media">Media</Link><Link href="/book">Book ICONIC</Link><Link href="/contact">Contact</Link></nav></details></div>
    </header>
    <main id="iconic-content">{children}</main>
    <footer className={s.footer}>
      <div className={s.footerTop}><div><img src={ICONIC_LOGO} alt="ICONIC" width={200} height={60}/><p>Music brings us here.<br/>Culture keeps us connected.</p></div><div><span className={s.eyebrow}>Explore</span>{NAV.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}</div><div><span className={s.eyebrow}>Be part of it</span><Link href="/access?intent=presale">Event updates</Link><Link href="/access?intent=vip">VIP & hospitality</Link><Link href="/book">Book ICONIC</Link><Link href="/media">Press & media</Link><Link href="/contact">Contact</Link></div></div>
      <div className={s.footerBottom}><span>ICONIC · Live entertainment & culture</span><span><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></span></div>
    </footer>
  </div>;
}
function Actions({children}:{children:ReactNode}) { return <div className={s.actions}>{children}</div>; }
function CTA({href,children,secondary=false}:{href:string;children:ReactNode;secondary?:boolean}) {return <Link className={secondary?s.secondary:s.primary} href={href}>{children}<span aria-hidden="true">↗</span></Link>;}
function Intro({eyebrow,title,body,children}:{eyebrow:string;title:string;body:string;children?:ReactNode}) {return <section className={s.intro}><div><span className={s.eyebrow}>{eyebrow}</span><h1>{title}</h1></div><div><p>{body}</p>{children}</div></section>;}
function Heading({label,title,href,link='Explore'}:{label:string;title:string;href?:string;link?:string}) {return <div className={s.sectionHead}><div><span className={s.eyebrow}>{label}</span><h2>{title}</h2></div>{href&&<Link className={s.textLink} href={href}>{link} <span aria-hidden="true">↗</span></Link>}</div>;}
function Opener({src,alt}:{src:string;alt:string}) {return <div className={s.opener}><img src={src} alt={alt} loading="eager" fetchPriority="high"/></div>;}
function Worlds({sponsorship=false}:{sponsorship?:boolean}) {return <div className={s.worlds} data-testid="flagship-worlds">{WORLDS.map(w=><Link className={s.worldCard} key={w.key} data-property={w.key} href={sponsorship?`/access?intent=sponsorship&event=${w.key}`:w.href} style={{'--world-accent':w.tone==='blush'?'#ddbdc8':'#d77964'} as React.CSSProperties}><div className={s.worldImage}><img src={w.src} alt={`${w.title} — original campaign artwork`} loading="lazy"/></div><div className={s.worldCopy}><span className={s.eyebrow}>{w.eyebrow}</span><h3>{w.title}</h3><p>{w.body}</p><span className={s.cardAction}>{sponsorship?'Discuss a partnership':w.action} <span aria-hidden="true">↗</span></span></div></Link>)}</div>;}
function Section({children,light=false,id}:{children:ReactNode;light?:boolean;id?:string}) {return <section id={id} className={light?s.lightSection:s.section}>{children}</section>;}
function Split({src,alt,label,title,children,reverse=false}:{src:string;alt:string;label:string;title:string;children:ReactNode;reverse?:boolean}) {return <section className={`${s.split} ${reverse?s.reverse:''}`}><div className={s.splitImage}><img src={src} alt={alt} loading="lazy"/></div><div className={s.splitCopy}><span className={s.eyebrow}>{label}</span><h2>{title}</h2>{children}</div></section>;}
function Closing({label,title,body,href,action}:{label:string;title:string;body:string;href:string;action:string}) {return <section className={s.closing}><div><span className={s.eyebrow}>{label}</span><h2>{title}</h2><p>{body}</p></div><CTA href={href}>{action}</CTA></section>;}
function Intake({intent,event,title,label,body}:{intent:string;event:string;title:string;label:string;body:string}) {return <Section id="inquiry"><div className={s.intake}><div><span className={s.eyebrow}>{label}</span><h2>{title}</h2><p>{body}</p><p className={s.note}>Submitting a request is not a booking or ticket confirmation. Our team will review the details and follow up.</p></div><div className={s.form}><AccessForm intent={intent} event={event}/></div></div></Section>;}

export function CinematicHome() {return <CinematicShell>
  <MotionCanvas/>
  <Intro eyebrow="ICONIC / LIVE ENTERTAINMENT & CULTURE" title="Be there." body="For the song you know by heart. For the night you talk about tomorrow. Find your next show, discover the people behind it, and take a piece of the experience home."><Actions><CTA href="/events">Explore events</CTA><CTA secondary href="/access?intent=presale">Get event updates</CTA></Actions></Intro>
  <Section id="worlds"><Heading label="The headline experiences" title="Different nights. Distinct worlds." href="/events" link="All events"/><Worlds/></Section>
  <Split src={ART.backstage} alt="ICONIC backstage campaign artwork with a microphone and production case" label="The ICONIC platform" title="The stage is only the beginning."><p>Live shows, creative work, music and the moments around them. Choose your way in.</p><div className={s.platformLinks}>{[['Live','Concerts & tours','/events'],['Experiences','Nightlife & hospitality','/experiences'],['Music','Development & performance','/music'],['Creators','People behind the culture','/creators'],['Media','Campaigns & storytelling','/media'],['Merch','Event & artist collections','/merch']].map(([title,body,href])=><Link key={href} href={href}><strong>{title}</strong><span>{body}</span><em aria-hidden="true">↗</em></Link>)}</div></Split>
  <Section light><Heading label="Nightmare on Channelside / Collections" title="Take the night with you." href="/merch" link="Explore merchandise"/><div className={s.collectionRow}>{COLLECTIONS.filter(c=>['21-savage','kodak-black','da-baby'].includes(c.slug)).map(c=><Link key={c.slug} href={`${MERCH_ROOT}/collection/${c.slug}`} className={s.collectionCard}><img src={COLLECTION_ART[c.slug]} alt={`${c.title} collection campaign artwork`} loading="lazy"/><div><h3>{c.title}</h3><span>Shop the collection ↗</span></div></Link>)}</div></Section>
  <Split src={ART.hospitality} alt="ICONIC hospitality concept artwork" label="Partnership possibilities" title="Your brand. In the room." reverse><p>Go beyond a logo on a screen. Explore event partnerships, guest experiences, content and merchandise built around the right audience.</p><Actions><CTA href="/partners">Explore partnerships</CTA></Actions></Split>
</CinematicShell>;}

export function CinematicEvents() {return <CinematicShell active="/events">
  <Opener src={ART.crowd} alt="ICONIC arena campaign artwork with an illuminated circular stage"/>
  <Intro eyebrow="ICONIC LIVE / EVENTS" title="Find your next night." body="Headline experiences and recurring series, each with a sound, a setting and an identity of its own. Explore a property for its latest announcements and access options."><Actions><CTA href="#worlds">Explore the lineup</CTA><CTA secondary href="/access?intent=presale">Get event updates</CTA></Actions></Intro>
  <Section id="worlds"><Heading label="Current flagships" title="Three ways into the night."/><Worlds/><p className={s.note}>Tour dates and venue details are announced on the individual property pages. Tour-update registration is not a ticket purchase.</p></Section>
  <Split src={ART.greekBall} alt="Greek Ball campaign artwork from The Ball Series" label="The Ball Series / Greek Ball" title="Dress for the occasion."><p>A season of formal and themed nights. Explore the individual Ball identities, the calendar and the details that make each one its own occasion.</p><CTA href="/ball-series">Explore The Ball Series</CTA></Split>
  <Section light><Heading label="Recurring series" title="Find your crowd."/><div className={s.series}><Link href="/series/21-plus"><span className={s.eyebrow}>21+ concert series</span><h3>Grown-ish</h3><p>Hip-hop, R&B and contemporary concert culture.</p><span className={s.textLink}>Explore the series ↗</span></Link><Link href="/series/30-plus"><span className={s.eyebrow}>30+ concert series</span><h3>Soul Session</h3><p>Live music for a grown audience.</p><span className={s.textLink}>Explore the series ↗</span></Link></div><div className={s.marketLinks}><span>Explore more</span><Link href="/atlanta">Atlanta ↗</Link><Link href="/southlake-arena">Southlake Arena ↗</Link><Link href="/new-york/resorts-world">New York ↗</Link></div></Section>
  <Closing label="Make it your night" title="Get closer to the experience." body="Request event updates or explore VIP and hospitality options for your selected property." href="/access?intent=vip" action="Explore VIP access"/>
</CinematicShell>;}

export function CinematicMusic() {return <CinematicShell active="/music">
  <Opener src={ART.world} alt="ICONIC music campaign artwork: performance runway and monumental stage"/>
  <Intro eyebrow="ICONIC MUSIC" title="Built around the sound." body="Artist development, release planning, DJ programming and performance opportunities. Bring the music. Tell us where you want it to go."><Actions><CTA href="#inquiry">Submit your music</CTA><CTA secondary href="/events">Explore live events</CTA></Actions></Intro>
  <Section light><Heading label="From the idea to the room" title="A clear next chapter."/><div className={s.process}>{[['01','Define the artist','Identity, audience and a clear creative direction.'],['02','Shape the release','Production strategy, collaborators, content and rollout.'],['03','Build the performance','Live presentation, DJ programming and relevant opportunities.']].map(([n,t,b])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></Section>
  <Split src={ART.dj} alt="ICONIC DJ-stage campaign artwork" label="Performance & programming" title="The room matters, too."><p>A release and a live set do different jobs. We look at the sound, the audience and the setting together—from performance preparation to event sound curation.</p><div className={s.chips}><span>Artist development</span><span>Production strategy</span><span>Release rollouts</span><span>DJ programming</span><span>Performance bookings</span></div><CTA href="/book">Discuss a booking</CTA></Split>
  <Intake intent="music" event="iconic-music" label="Music submission" title="Let us hear it." body="Share your music links, city, current releases and the kind of support or performance opportunity you are looking for."/>
</CinematicShell>;}

export function CinematicCreators() {return <CinematicShell active="/creators">
  <Opener src={ART.artist} alt="ICONIC creator campaign artwork: performer silhouette facing an arena"/>
  <Intro eyebrow="ICONIC CREATORS" title="Bring your point of view." body="Artists, performers, photographers, filmmakers, hosts, producers and designers. The work matters. So does the person behind it."><Actions><CTA href="#inquiry">Introduce yourself</CTA><CTA secondary href="/media">Explore media</CTA></Actions></Intro>
  <Section light><Heading label="Creative disciplines" title="In front. Behind. Everywhere."/><div className={s.disciplines}><article><h3>In front of the crowd.</h3><p>Music artists, DJs, performers and hosts shaping the energy of the room.</p></article><article><h3>Behind the lens.</h3><p>Photographers, videographers and visual artists giving the moment its perspective.</p></article><article><h3>Behind the idea.</h3><p>Producers, designers and cultural tastemakers turning a direction into something people can experience.</p></article></div></Section>
  <Split src={ART.reveal} alt="ICONIC creative-stage concept artwork with portrait screens" label="Creative opportunity" title="Good work deserves the right setting."><p>Tell us what you make and what you need next. Opportunities may include live programming, creative projects, brand presentation, content capture and aligned partnerships.</p><ol className={s.steps}><li>Share your work and your discipline.</li><li>Our team reviews fit and current opportunities.</li><li>Discuss scope, availability and next steps.</li></ol></Split>
  <Intake intent="creator" event="iconic-creators" label="Creator submission" title="Show us your work." body="Include portfolio links, your market, your discipline and what you would like to build with ICONIC. An application does not imply representation."/>
</CinematicShell>;}

export function CinematicExperiences() {return <CinematicShell active="/experiences">
  <Opener src={ART.hospitality} alt="ICONIC hospitality and guest-experience concept artwork"/>
  <Intro eyebrow="ICONIC EXPERIENCES" title="Make more of the night." body="The arrival. The room. The people you meet. Explore nightlife, cultural experiences and curated social connection beyond the main stage."><Actions><CTA href="/social">Explore ICONIC Social</CTA><CTA secondary href="/book">Plan an experience</CTA></Actions></Intro>
  <Section light><Heading label="Choose your setting" title="A different kind of together."/><div className={s.disciplines}><article><span className={s.eyebrow}>Nightlife</span><h3>ICONIC Nights</h3><p>Music-led nights with considered rooms, guest experiences and atmosphere.</p><Link className={s.textLink} href="/access?intent=vip">Request access ↗</Link></article><article><span className={s.eyebrow}>Immersive culture</span><h3>ICONIC Experiences</h3><p>Art direction, sound, performance and hospitality designed as one experience.</p><Link className={s.textLink} href="/events">Explore events ↗</Link></article><article><span className={s.eyebrow}>Connection</span><h3>ICONIC Social</h3><p>Curated spaces for creators, operators, brands and cultural communities.</p><Link className={s.textLink} href="/social">Explore Social ↗</Link></article></div></Section>
  <Split src={ART.runway} alt="ICONIC campaign artwork illustrating an arrival runway and stage" label="From arrival to after-hours" title="Every detail sets the tone."><p>Arrival, lighting, music, service and guest flow all shape the experience. Talk to ICONIC about private, corporate, brand or venue programming.</p><Actions><CTA href="/book">Book ICONIC</CTA><CTA secondary href="/access?intent=vip">VIP & hospitality</CTA></Actions></Split>
</CinematicShell>;}

export function CinematicPartners() {return <CinematicShell active="/partners">
  <Opener src={ART.symphonic} alt="ICONIC platform campaign artwork illustrating the scale of a live experience"/>
  <Intro eyebrow="ICONIC / PARTNERSHIPS" title="Be part of the experience." body="Explore partnerships around the moments people come for: the show, the arrival, the hospitality, the content and the merchandise."><Actions><CTA href="#inquiry">Start a conversation</CTA><CTA secondary href="#properties">Explore properties</CTA></Actions></Intro>
  <Section light><Heading label="Partnership possibilities" title="More than a placement."/><div className={s.partnerPillars}><article><span className={s.eyebrow}>01 / On the ground</span><h3>In the room.</h3><p>On-site activations, ticket allocations, guest experiences and category opportunities, subject to each property's available rights.</p></article><article><span className={s.eyebrow}>02 / In the culture</span><h3>In the conversation.</h3><p>Content collaborations, creator-led storytelling, campaign integration and event documentation.</p></article><article><span className={s.eyebrow}>03 / Beyond the show</span><h3>In their hands.</h3><p>Merchandise collaborations, food and beverage opportunities and hospitality extensions where available.</p></article></div></Section>
  <Section id="properties"><Heading label="Explore by property" title="The right fit comes first."/><Worlds sponsorship/><p className={s.note}>Partnership formats, category rights and hospitality inventory are scoped separately for each property. No partnership is implied by concept artwork.</p></Section>
  <Intake intent="sponsorship" event="iconic-partnerships" label="Partnership inquiry" title="Tell us what you have in mind." body="Share your brand, target audience, preferred property or market, timing and the kind of experience you want to create."/>
</CinematicShell>;}

export function CinematicMedia() {return <CinematicShell>
  <Opener src={ART.media} alt="ICONIC media-production and archive concept artwork"/>
  <Intro eyebrow="ICONIC MEDIA + ARCHIVE" title="The story goes on." body="Photography, recap films, editorial coverage and campaign creative. Explore media collaboration or request approved materials for a specific property."><Actions><CTA href="#inquiry">Request media</CTA><CTA secondary href="/creators">Join the creative network</CTA></Actions></Intro>
  <Section light><Heading label="The work" title="Different ways to tell it."/><div className={s.disciplines}><article><h3>Photography.</h3><p>People, atmosphere, performance and details captured with a clear point of view.</p></article><article><h3>Film & editorial.</h3><p>Recaps, short-form stories and documentation that keep the experience in view.</p></article><article><h3>Campaign creative.</h3><p>Original visual worlds for announcements, property storytelling and future releases.</p></article></div><p className={s.note}>The cinematic arena images on this website are campaign concepts. They are not presented as documentary photographs or proof of past event attendance.</p></Section>
  <Intake intent="media" event="iconic-media-archive" label="Media request" title="Find the right material." body="Include the property, publication or project, requested materials and intended use. Press access, licensing and image permissions require confirmation."/>
</CinematicShell>;}

export async function CinematicMerch() {
  const catalog = await getMerchCatalog();
  const active = new Set(catalog.collections.map(c=>c.slug));
  const selections = COLLECTIONS.map(c=>({collection:c,product:catalog.products.find(p=>p.collection_slug===c.slug&&p.is_active&&p.primary_image_url)})).filter(x=>x.product);
  return <CinematicShell active="/merch">
    <section className={s.merchIntro}><div><span className={s.eyebrow}>ICONIC MERCH / NIGHTMARE ON CHANNELSIDE</span><h1>Wear the night.</h1><p>Artist collections. Tampa editions. Pieces from the world of Nightmare on Channelside.</p><Actions><CTA href={`${MERCH_ROOT}/shop`}>Shop merchandise</CTA><CTA secondary href={`${MERCH_ROOT}/cart`}>View your cart</CTA></Actions></div><img src={COLLECTION_ART['all-artists']} alt="Nightmare on Channelside full-lineup collection campaign artwork" loading="eager" fetchPriority="high"/></section>
    <Section><Heading label="Artist collections" title="Choose your collection."/><div className={s.artistCollections}>{COLLECTIONS.filter(c=>active.has(c.slug)).map(c=><Link key={c.slug} href={`${MERCH_ROOT}/collection/${c.slug}`} className={s.collectionCard}><img src={COLLECTION_ART[c.slug]} alt={`${c.title} collection artwork`} loading="lazy"/><div><h3>{c.title}</h3><span>Explore collection ↗</span></div></Link>)}</div>{catalog.source==='unavailable'&&<p role="status" className={s.notice}>The collection is temporarily unavailable. Please try the shop again shortly or contact us for help.</p>}</Section>
    {selections.length>0&&<Section light><Heading label="From the collection" title="Find your piece." href={`${MERCH_ROOT}/shop`} link="Shop all pieces"/><div className={s.products}>{selections.map(({collection,product:p})=>p&&<Link key={p.shopify_product_id} className={s.product} href={`${MERCH_ROOT}/product/${p.sku}`} data-product-id={p.shopify_product_id}><div><img src={p.primary_image_url!} alt={p.title} loading="lazy"/></div><span className={s.eyebrow}>{collection.title}</span><h3>{p.title}</h3><p>From {formatPrice(p.price_cents)} <span>View options ↗</span></p></Link>)}</div></Section>}
    <Section><Heading label="Tampa & event editions" title="The city. The occasion."/><div className={s.eventCollections}>{[{slug:'tampa',title:'Tampa'},{slug:'nightmare-on-channelside',title:'Nightmare on Channelside'}].filter(c=>active.has(c.slug)).map(c=><Link key={c.slug} className={s.collectionCard} href={`${MERCH_ROOT}/collection/${c.slug}`}><img src={COLLECTION_ART[c.slug]} alt={`${c.title} collection campaign artwork`} loading="lazy"/><div><h3>{c.title}</h3><span>Explore collection ↗</span></div></Link>)}</div></Section>
    <Section light><Heading label="On the horizon" title="Hear about the next drop."/><div className={s.dropLinks}>{WORLDS.filter(w=>w.key!=='tampa-halloween').map(w=><Link href={`/access?intent=merch&event=${w.key}`} key={w.key}><span className={s.eyebrow}>Drop notifications</span><h3>{w.title}</h3><span>Join the update list ↗</span></Link>)}</div><p className={s.note}>Upcoming-tour registrations are notification requests. No product purchase or release date is implied.</p></Section>
    <Closing label="Your order" title="Choose the piece. Check the details." body="Review the item, selected variant, price and delivery information before completing checkout." href={`${MERCH_ROOT}/cart`} action="View your cart"/>
  </CinematicShell>;
}
