import Link from "next/link";
import type { ReactNode } from "react";

export const C={black:"#030306",panel:"rgba(13,11,20,.88)",panel2:"rgba(20,17,31,.78)",white:"#fbfaff",muted:"rgba(245,242,255,.62)",faint:"rgba(255,255,255,.105)",gold:"#cbbcff",red:"#ff4f9f"};
const navLink={color:"rgba(255,255,255,.62)",textDecoration:"none",fontFamily:"Arial,sans-serif",fontSize:9,fontWeight:900,letterSpacing:".14em",textTransform:"uppercase" as const};

export function Shell({children}:{children:ReactNode}){return <main className="iconic-shell" style={{minHeight:"100vh",color:C.white}}><nav style={{position:"sticky",top:0,zIndex:50,minHeight:72,padding:"0 clamp(18px,4vw,56px)",display:"flex",alignItems:"center",justifyContent:"space-between",gap:20,background:"rgba(3,3,6,.78)",borderBottom:`1px solid ${C.faint}`,backdropFilter:"blur(26px) saturate(150%)"}}><Link href="/" style={{color:C.white,textDecoration:"none",display:"flex",alignItems:"center",gap:11}}><span style={{width:10,height:10,background:"linear-gradient(135deg,#8d5cff,#ff4fa7)",boxShadow:"0 0 22px rgba(155,92,255,.7)",transform:"rotate(45deg)",display:"inline-block"}}/><strong style={{fontFamily:"Georgia,serif",fontSize:24,letterSpacing:".08em"}}>ICONIC</strong></Link><div style={{display:"flex",gap:"clamp(9px,1.7vw,22px)",alignItems:"center",flexWrap:"wrap",justifyContent:"flex-end"}}><Link href="/atlanta/halloween" style={navLink}>Nightmare</Link><Link href="/atlanta/bravo" style={navLink}>BRAVO</Link><Link href="/series/21-plus" style={navLink}>GROWN-ISH</Link><Link href="/series/30-plus" style={navLink}>Soul Session</Link><Link href="/new-york/resorts-world" style={navLink}>New York</Link><Link href="/las-vegas" style={navLink}>Vegas</Link></div></nav>{children}<footer style={{position:"relative",zIndex:2,padding:"44px clamp(20px,5vw,72px)",borderTop:`1px solid ${C.faint}`,display:"flex",justifyContent:"space-between",gap:24,flexWrap:"wrap",background:"rgba(0,0,0,.35)"}}><div><strong style={{fontFamily:"Georgia,serif",fontSize:25}}>ICONIC.</strong><div style={{marginTop:8,color:C.muted,fontSize:9,fontWeight:900,letterSpacing:".18em",textTransform:"uppercase"}}>Concerts · Festivals · Arena Events</div></div><div style={{color:C.muted,fontSize:10,fontWeight:800,letterSpacing:".12em",textTransform:"uppercase"}}>Atlanta · New York · Las Vegas Coming Soon</div></footer></main>}

export function Hero({eyebrow,title,sub,accent="#9b5cff",children}:{eyebrow:string;title:string;sub:string;accent?:string;children?:ReactNode}){return <section style={{minHeight:"76vh",padding:"120px clamp(22px,6vw,90px) 74px",display:"flex",alignItems:"end",position:"relative",overflow:"hidden",background:`radial-gradient(circle at 78% 18%,${accent}35,transparent 24%),radial-gradient(circle at 10% 90%,rgba(255,63,164,.12),transparent 28%),#030306`}}><div className="light-beam" style={{right:"4%",top:"-22%"}}/><div style={{position:"absolute",inset:0,opacity:.13,backgroundImage:"linear-gradient(rgba(255,255,255,.04) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.04) 1px,transparent 1px)",backgroundSize:"76px 76px"}}/><div style={{position:"relative",zIndex:2,width:"100%",maxWidth:1450,margin:"0 auto"}}><div style={{display:"flex",alignItems:"center",gap:10,color:"#d8ccff",fontSize:9,fontWeight:900,letterSpacing:".31em",textTransform:"uppercase",marginBottom:18}}><span className="pulse-dot"/>{eyebrow}</div><h1 className="neon-text" style={{margin:0,maxWidth:1250,fontFamily:"Georgia,serif",fontSize:"clamp(62px,11vw,165px)",lineHeight:.8,letterSpacing:"-.06em"}}>{title}</h1><p style={{margin:"34px 0 0",maxWidth:720,color:C.muted,fontSize:"clamp(14px,1.5vw,18px)",lineHeight:1.8}}>{sub}</p>{children&&<div style={{marginTop:34}}>{children}</div>}</div></section>}

export function Button({href,children,ghost=false}:{href:string;children:ReactNode;ghost?:boolean}){return <Link href={href} style={{display:"inline-flex",minHeight:50,alignItems:"center",justifyContent:"center",padding:"0 26px",marginRight:10,marginBottom:10,borderRadius:999,textDecoration:"none",border:ghost?`1px solid ${C.faint}`:"1px solid rgba(255,255,255,.16)",background:ghost?"rgba(255,255,255,.035)":"linear-gradient(110deg,#f5f2ff,#bba7ff 42%,#ff76bf)",color:ghost?C.white:C.black,fontSize:9,fontWeight:900,letterSpacing:".17em",textTransform:"uppercase",boxShadow:ghost?"none":"0 14px 40px rgba(155,92,255,.22)"}}>{children}</Link>}

export function Section({eyebrow,title,children,dark=false}:{eyebrow:string;title:string;children:ReactNode;dark?:boolean}){return <section style={{position:"relative",zIndex:2,padding:"96px clamp(22px,6vw,90px)",background:dark?"rgba(255,255,255,.018)":"transparent",borderTop:`1px solid ${C.faint}`}}><div style={{maxWidth:1450,margin:"0 auto"}}><div style={{color:"#cdbfff",fontSize:9,fontWeight:900,letterSpacing:".30em",textTransform:"uppercase",marginBottom:16}}>{eyebrow}</div><h2 style={{margin:"0 0 42px",maxWidth:1050,fontFamily:"Georgia,serif",fontSize:"clamp(44px,6vw,90px)",lineHeight:.9,letterSpacing:"-.035em"}}>{title}</h2>{children}</div></section>}

export function InfoGrid({items}:{items:{label:string;value:string;body?:string}[]}){return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:14}}>{items.map(x=><div className="glass market-card" key={x.label} style={{padding:28,borderRadius:22}}><div style={{color:"#c9bbff",fontSize:8,fontWeight:900,letterSpacing:".19em",textTransform:"uppercase"}}>{x.label}</div><div style={{marginTop:14,fontFamily:"Georgia,serif",fontSize:30,lineHeight:1.03}}>{x.value}</div>{x.body&&<p style={{color:C.muted,fontSize:13,lineHeight:1.7,margin:"14px 0 0"}}>{x.body}</p>}</div>)}</div>}

export function Calendar({rows,status="2027 WORKING CALENDAR"}:{rows:{month:string;date:string;anchor:string}[];status?:string}){return <div className="glass" style={{borderRadius:22,overflow:"hidden"}}><div style={{padding:"20px 24px",color:"#d2c5ff",fontSize:8,fontWeight:900,letterSpacing:".22em",textTransform:"uppercase",borderBottom:`1px solid ${C.faint}`}}>{status}</div>{rows.map((r,i)=><div key={`${r.month}-${i}`} style={{display:"grid",gridTemplateColumns:"72px minmax(100px,145px) 1fr",gap:18,padding:"18px 22px",borderBottom:i===rows.length-1?"none":`1px solid ${C.faint}`,alignItems:"center"}}><strong style={{fontSize:10,color:C.white}}>{r.month}</strong><span style={{color:"#d7caff",fontSize:10,fontWeight:900,letterSpacing:".08em"}}>{r.date}</span><span style={{color:C.muted,fontSize:9,fontWeight:800,letterSpacing:".09em",textTransform:"uppercase"}}>{r.anchor}</span></div>)}</div>}

export const ny21=[{month:"JAN",date:"JAN 09 · HOLD",anchor:"WINTER OPEN"},{month:"FEB",date:"FEB 20 · HOLD",anchor:"WINTER"},{month:"MAR",date:"MAR 06 · HOLD",anchor:"SPRING"},{month:"APR",date:"APR 10 · HOLD",anchor:"SPRING"},{month:"MAY",date:"MAY 22 · HOLD",anchor:"MEMORIAL WINDOW"},{month:"JUN",date:"JUN 26 · HOLD",anchor:"SUMMER"},{month:"JUL",date:"JUL 03 · HOLD",anchor:"JULY 4TH"},{month:"AUG",date:"AUG 14 · HOLD",anchor:"LATE SUMMER"},{month:"SEP",date:"SEP 11 · HOLD",anchor:"FALL"},{month:"OCT",date:"OCT 09 · HOLD",anchor:"FALL"},{month:"NOV",date:"NOV 13 · HOLD",anchor:"FALL"},{month:"DEC",date:"DEC 04 · HOLD",anchor:"HOLIDAY"}];
export const ny30=[{month:"JAN",date:"JAN 30 · HOLD",anchor:"WINTER"},{month:"FEB",date:"FEB 13 · HOLD",anchor:"VALENTINE'S"},{month:"MAR",date:"MAR 27 · HOLD",anchor:"SPRING"},{month:"APR",date:"APR 24 · HOLD",anchor:"SPRING"},{month:"MAY",date:"MAY 08 · HOLD",anchor:"MOTHER'S DAY"},{month:"JUN",date:"JUN 19 · HOLD",anchor:"JUNETEENTH"},{month:"JUL",date:"JUL 31 · HOLD",anchor:"SUMMER"},{month:"AUG",date:"AUG 28 · HOLD",anchor:"LATE SUMMER"},{month:"SEP",date:"SEP 18 · HOLD",anchor:"FALL"},{month:"OCT",date:"OCT 23 · HOLD",anchor:"FALL"},{month:"NOV",date:"NOV 27 · HOLD",anchor:"THANKSGIVING"},{month:"DEC",date:"DEC 18 · HOLD",anchor:"HOLIDAY"}];
