insert into public.noc_campaign_config(config_key,config_value,is_secret,notes)
values(
  'personnel_packet_manifest_20260919',
  $manifest$
{"version":"2026.09","effective_date":"2026-09-19","rule":"Send one full role-specific packet only. Do not send the generic master packet as the primary onboarding document.","directory_doc_id":"1ZjdeJvO7CObmk5IWMuOnsvdvD8rx5YhdRF0rHC_4LHk","directory_pdf_id":"152YoelrqnCol6mKPyUlkXUKORA5cPvSv","packets":{"promoter_commission":{"doc_id":"12l1uBObJRa62ipLdrV00DnJ7Luq3cL8QqDSpdnt6-30","pdf_id":"1FBjPxwy7S9rf_8dcDCBl7NlOQK71nmgu","form":"/partners/apply/promoter-commission"},"promoter_comp":{"doc_id":"1dyDLYXVTBmOqRrDa5mWAjoyY4A9j_4THTNpC987TWNs","pdf_id":"1OYXSEv1q8qZT2IyFJDM9Upv9W9-YbYz9","form":"/partners/apply/promoter-comp"},"general_ambassador":{"doc_id":"1Ij89FWHbtMQKXfIgJDb2cHXyz8UXV874MpBPT9GTCeg","pdf_id":"1jgLbPNBKPUrO6g-9kvf4SLbCLCq9uLNs","form":"/partners/apply/ambassador-model"},"model":{"doc_id":"1jEjGlJGf7tBv9z4F97Bc5oL1Youz0R1_HEQ6u5cGKZM","pdf_id":"1SIbL_k0pI71XEDFtUeadJWxs9KoA1bYx","form":"/partners/apply/ambassador-model"},"podcast_partner":{"doc_id":"13-zR6htjxEodQQzQD-7wAiF9s7jDWwYFmt3yAazRGpo","pdf_id":"17BA7Itu-c3bLmJfKLdMLfaGolr50joKN","form":"/partners/apply/podcast"},"dj_promo":{"doc_id":"1ghDpZc8-7uBeLB_5LhfPRCQIQcZaIQJSfUrt-L-Ua5g","pdf_id":"1eyzifi2_Pu6UvKm86dTChJZiZ2RxTkDQ","form":"/partners/apply/dj-promo"},"dj_performance":{"doc_id":"1M3CLAerUM6O6t0y1na92a89QSo9zQFP8A4JzFVt85lM","pdf_id":"148GYLh6nqTBbhauxdA2gdEQJyLonNOKy","form":"/partners/apply/dj-performance"},"host_promo":{"doc_id":"19vc0vf6xQ51A5iz-AwR1G6geDnJjmTeWTBJw2i5pKrI","pdf_id":"1Bx9KFA-C2_RCP7TX9-AD81k9gMuuPYSf","form":"/partners/apply/host-promo"},"host_performance":{"doc_id":"14-YDEmSJtUgaCykdQ5ljKAAVzpIk3P1ckKBOm2oD0Bk","pdf_id":"1fSsmpKy1BFBylQMCDbp43tLmDsCLF9kl","form":"/partners/apply/host-performance"},"street_team":{"doc_id":"1MhfCE4CI4Fx0g9LduTf02qp3OX5v_xH_rIVA0pkQkc8","pdf_id":"1ZTU7ZGvTe9aUiTn2Br4O6ibY2UXL6yUP","form":"/partners/apply/street-team"}}}
  $manifest$::jsonb,
  false,
  'Role-keyed full personnel packet manifest for automated onboarding.'
)
on conflict(config_key) do update set config_value=excluded.config_value,notes=excluded.notes,updated_at=now();