-- NIGHTMARE ON CHANNELSIDE partner operations backend
-- Applied to production Supabase on 2026-09-19.
create extension if not exists pgcrypto;

create table if not exists public.noc_partner_applications (
  id uuid primary key default gen_random_uuid(),
  full_name text not null check (char_length(full_name) between 2 and 120),
  display_name text,
  email text not null check (char_length(email) between 5 and 254),
  phone text,
  instagram text,
  tiktok text,
  city text not null check (char_length(city) between 2 and 120),
  requested_role text not null check (requested_role in (
    'promoter_commission','promoter_comp','ambassador_model','podcast_partner',
    'dj_promo','host_promo','dj_performance','host_performance','street_team'
  )),
  availability text,
  notes text,
  referral_source text,
  source_url text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  consent_to_contact boolean not null default false,
  status text not null default 'new' check (status in ('new','reviewing','approved','waitlist','declined','converted')),
  reviewed_at timestamptz,
  reviewed_by text,
  converted_partner_id uuid,
  created_at timestamptz not null default now()
);
create index if not exists noc_partner_applications_status_created_idx on public.noc_partner_applications(status,created_at desc);
create index if not exists noc_partner_applications_role_city_idx on public.noc_partner_applications(requested_role,city);
alter table public.noc_partner_applications enable row level security;
revoke all on public.noc_partner_applications from anon,authenticated;
grant insert(full_name,display_name,email,phone,instagram,tiktok,city,requested_role,availability,notes,referral_source,source_url,utm_source,utm_medium,utm_campaign,utm_content,consent_to_contact)
  on public.noc_partner_applications to anon,authenticated;
drop policy if exists "noc public partner application insert" on public.noc_partner_applications;
create policy "noc public partner application insert" on public.noc_partner_applications for insert to anon,authenticated
with check(status='new' and reviewed_at is null and reviewed_by is null and converted_partner_id is null);

create table if not exists public.noc_campaign_partners (
  id uuid primary key default gen_random_uuid(),
  partner_number bigint generated by default as identity unique,
  event_key text not null default 'nightmare_on_channelside_2026',
  legal_name text not null,
  display_name text,
  email text,
  phone text,
  instagram text,
  tiktok text,
  city text not null,
  role text not null check (role in ('promoter_commission','promoter_comp','ambassador_model','podcast_partner','dj_promo','host_promo','dj_performance','host_performance','street_team')),
  compensation_model text not null check (compensation_model in ('commission','comp_tickets','noncash_plus_optional_commission','flat_fee','performance_fee','verified_shift')),
  flat_fee numeric(12,2) not null default 0 check(flat_fee>=0),
  commission_rate numeric(6,5) not null default 0 check(commission_rate between 0 and 1),
  comp_tickets integer not null default 0 check(comp_tickets>=0),
  promo_code text unique,
  tracking_url text,
  merch_code text unique,
  agreement_status text not null default 'not_sent' check(agreement_status in ('not_sent','sent','signed','waived')),
  tax_status text not null default 'n_a' check(tax_status in ('n_a','needed','received','approved')),
  start_date date not null default current_date,
  status text not null default 'prospect' check(status in ('prospect','invited','accepted','paperwork','active','payment_hold','completed','removed')),
  owner text,
  next_action text,
  due_date date,
  credential_allocation text,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists noc_campaign_partners_status_idx on public.noc_campaign_partners(status);
create index if not exists noc_campaign_partners_role_city_idx on public.noc_campaign_partners(role,city);
create index if not exists noc_campaign_partners_due_idx on public.noc_campaign_partners(due_date) where status not in ('completed','removed');
alter table public.noc_campaign_partners enable row level security;
revoke all on public.noc_campaign_partners from anon,authenticated;

create or replace function public.noc_partner_code() returns trigger language plpgsql set search_path='' as $$
declare city_code text; role_code text; suffix text;
begin
  city_code:=upper(left(regexp_replace(coalesce(new.city,'XXX'),'[^A-Za-z]','','g'),3));
  role_code:=case new.role when 'promoter_commission' then 'PRO' when 'promoter_comp' then 'CMP' when 'ambassador_model' then 'AMB' when 'podcast_partner' then 'POD' when 'dj_promo' then 'DJP' when 'host_promo' then 'HST' when 'dj_performance' then 'DJS' when 'host_performance' then 'HSP' when 'street_team' then 'STR' else 'PRT' end;
  suffix:=lpad(new.partner_number::text,5,'0');
  if new.promo_code is null or new.promo_code='' then new.promo_code:='NOC-'||city_code||'-'||role_code||'-'||suffix; end if;
  if new.tracking_url is null or new.tracking_url='' then new.tracking_url:='https://iconic-atl.com/go/'||new.promo_code; end if;
  if new.merch_code is null or new.merch_code='' then new.merch_code:='NOCMERCH-'||suffix; end if;
  new.updated_at:=now();
  return new;
end $$;
drop trigger if exists trg_noc_partner_code on public.noc_campaign_partners;
create trigger trg_noc_partner_code before insert or update of city,role,promo_code,tracking_url,merch_code on public.noc_campaign_partners for each row execute function public.noc_partner_code();

create table if not exists public.noc_partner_deliverables (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.noc_campaign_partners(id) on delete cascade,
  milestone text not null,
  due_date date,
  content_format text,
  asset_ref text,
  caption_direction text,
  cta text,
  required boolean not null default true,
  status text not null default 'not_due' check(status in ('not_due','due','submitted','approved','revision','missed','waived')),
  proof_url text,
  proof_submitted_at timestamptz,
  qa_notes text,
  approved_by text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(partner_id,milestone)
);
create index if not exists noc_partner_deliverables_due_idx on public.noc_partner_deliverables(due_date,status);
create index if not exists noc_partner_deliverables_partner_idx on public.noc_partner_deliverables(partner_id,status);
alter table public.noc_partner_deliverables enable row level security;
revoke all on public.noc_partner_deliverables from anon,authenticated;

create table if not exists public.noc_partner_payments (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.noc_campaign_partners(id) on delete cascade,
  budget_category text,
  payment_type text not null check(payment_type in ('flat_fee','performance_fee','shift','commission','reimbursement','bonus')),
  milestone text,
  due_date date,
  amount_due numeric(12,2) not null default 0 check(amount_due>=0),
  amount_paid numeric(12,2) not null default 0 check(amount_paid>=0),
  status text not null default 'planned' check(status in ('planned','qa_hold','approved','scheduled','paid','void')),
  qa_status text not null default 'not_due' check(qa_status in ('not_due','due','submitted','approved','revision','missed','waived')),
  approved_by text,
  approved_at timestamptz,
  paid_at timestamptz,
  payment_method text,
  payment_reference text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists noc_partner_payments_due_idx on public.noc_partner_payments(status,due_date);
create index if not exists noc_partner_payments_partner_idx on public.noc_partner_payments(partner_id,status);
alter table public.noc_partner_payments enable row level security;
revoke all on public.noc_partner_payments from anon,authenticated;

create table if not exists public.noc_campaign_budget (
  category text primary key,
  planned_amount numeric(12,2) not null check(planned_amount>=0),
  owner text,
  payment_rule text,
  performance_rule text,
  status text not null default 'active' check(status in ('active','hold','closed')),
  updated_at timestamptz not null default now()
);
alter table public.noc_campaign_budget enable row level security;
revoke all on public.noc_campaign_budget from anon,authenticated;

create table if not exists public.noc_campaign_suballocations (
  id uuid primary key default gen_random_uuid(),
  parent_category text not null references public.noc_campaign_budget(category) on update cascade,
  subcategory text not null,
  working_cap numeric(12,2) not null default 0 check(working_cap>=0),
  payment_rule text,
  notes text,
  unique(parent_category,subcategory)
);
create index if not exists noc_campaign_suballocations_parent_idx on public.noc_campaign_suballocations(parent_category);
alter table public.noc_campaign_suballocations enable row level security;
revoke all on public.noc_campaign_suballocations from anon,authenticated;

create table if not exists public.noc_campaign_targets (
  id uuid primary key default gen_random_uuid(),
  dimension_type text not null check(dimension_type in ('role','city')),
  dimension_key text not null,
  total_target integer not null default 0 check(total_target>=0),
  cash_paid_target integer not null default 0 check(cash_paid_target>=0),
  no_upfront_cash_target integer not null default 0 check(no_upfront_cash_target>=0),
  notes text,
  unique(dimension_type,dimension_key)
);
alter table public.noc_campaign_targets enable row level security;
revoke all on public.noc_campaign_targets from anon,authenticated;

create table if not exists public.noc_promo_codes (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid references public.noc_campaign_partners(id) on delete cascade,
  promo_code text not null unique,
  code_type text not null default 'partner' check(code_type in ('partner','street','campus','paid_media','podcast','culture')),
  city text,
  role text,
  channel text,
  tracking_url text not null,
  ticketmaster_offer_code text,
  shopify_merch_code text,
  merch_discount_pct numeric(5,2) not null default 75 check(merch_discount_pct between 0 and 100),
  merch_max_items integer not null default 4 check(merch_max_items>=0),
  merch_single_use boolean not null default true,
  status text not null default 'draft' check(status in ('draft','active','paused','expired')),
  clicks bigint not null default 0,
  leads bigint not null default 0,
  verified_sales bigint not null default 0,
  verified_revenue numeric(14,2) not null default 0,
  last_sync_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists noc_promo_codes_partner_idx on public.noc_promo_codes(partner_id);
create index if not exists noc_promo_codes_status_idx on public.noc_promo_codes(status);
alter table public.noc_promo_codes enable row level security;
revoke all on public.noc_promo_codes from anon,authenticated;

create or replace function public.noc_sync_promo_code() returns trigger language plpgsql set search_path='' as $$
begin
  insert into public.noc_promo_codes(partner_id,promo_code,code_type,city,role,channel,tracking_url,shopify_merch_code,status)
  values(new.id,new.promo_code,'partner',new.city,new.role,'partner',new.tracking_url,new.merch_code,case when new.status='active' then 'active' else 'draft' end)
  on conflict(promo_code) do update set partner_id=excluded.partner_id,city=excluded.city,role=excluded.role,tracking_url=excluded.tracking_url,shopify_merch_code=excluded.shopify_merch_code,status=excluded.status,updated_at=now();
  return new;
end $$;
drop trigger if exists trg_noc_sync_promo_code on public.noc_campaign_partners;
create trigger trg_noc_sync_promo_code after insert or update of city,role,promo_code,tracking_url,merch_code,status on public.noc_campaign_partners for each row execute function public.noc_sync_promo_code();

create table if not exists public.noc_street_shifts (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.noc_campaign_partners(id) on delete cascade,
  city text not null,
  assigned_zone text not null,
  supervisor text,
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  actual_start timestamptz,
  actual_end timestamptz,
  tracking_code text,
  materials_issued integer not null default 0 check(materials_issued>=0),
  materials_distributed integer not null default 0 check(materials_distributed>=0),
  proof_url text,
  qr_scans integer not null default 0 check(qr_scans>=0),
  status text not null default 'scheduled' check(status in ('scheduled','active','proof_submitted','approved','rejected','paid','cancelled')),
  supervisor_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists noc_street_shifts_schedule_idx on public.noc_street_shifts(city,scheduled_start,status);
alter table public.noc_street_shifts enable row level security;
revoke all on public.noc_street_shifts from anon,authenticated;

create table if not exists public.noc_campaign_config (
  config_key text primary key,
  config_value jsonb not null,
  is_secret boolean not null default false,
  notes text,
  updated_at timestamptz not null default now()
);
alter table public.noc_campaign_config enable row level security;
revoke all on public.noc_campaign_config from anon,authenticated;
